function Array({ accountDescription, detailDescription }) {
  return (
    <div>
      <table>
        <tr>
          <td>Date</td>
          <td>Description</td>
          <td>&nbsp;</td>
          <td>Amout</td>
          <td>Balance</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>{accountDescription.date}</td>
          <td></td>
          <td>&nbsp;</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td>&nbsp;</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td>&nbsp;</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td>&nbsp;</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </table>
    </div>
  )
}
